import turtle
s = turtle.getscreen()
t = turtle.Turtle()
turtle.bgcolor ("lightblue")
t.pen(pencolor= "black", fillcolor= "yellow", pensize=5, speed=9)
t.begin_fill()
t.circle(150)
t.end_fill()
t.penup()
t.lt(90)
t.fd(100)
t.pendown()
t.fd(20)
t.rt(90)
t.penup()
t.fd(50)
t.lt(90)
t.fd(50)
t.pendown()
t.fd(50)
t.penup()
t.lt (90)
t.fd (100)
t.lt (90)
t.pendown()
t.fd(50)
t.penup()
t.goto(-38,60)
t.pendown()
t.circle(40,180)
t.penup()
t.goto (-170,-100)
t.write ("BE HAPPY", font=("Cooper Black", 50,))